### ISSUE TITLE
zápisky z audia (testování přístupnosti), co nám poslal Michal (slibuju, že rozsekám, ale aby to někde bylo)

### ISSUE THREAD

**Issue by MartaMachova** [Nepanikar/nepanikar#182]
nepanikar-pristupnost

home - kromě jednoho obrázku a spodního menu nepozná, co je na obrazovce 
---------------------
název - ok (obrázek)
rychlá pomoc - je jako obrázek, potřeboval by aby to bylo tlačíko, neví, jestli na to má/může kliknout
dlaždice - neví, co je to za element
panely dole menu - ok (karta)

kontakty na pomoc
----------------------------
dlaždice - nerozezná, co je to za prvky, jestli na to může kliknout

chat
--------------------
navigace: Home -> Rychlá pomoc -> Kontakty na pomoc: Chat -> Nepanikař
-hodí do prohlížeče, což nevyhovuje - lépe web view, aby zůstalo v aplikaci (nepřehledné, konverzace zůstává v prohlížeči) - aby to zůstalo v aplikaci

Ahoj, jak se dnes cítíš?
-------------------------
navigace: Home -> smajlíci
-po kliknutí na smajlíka nepozná, že se něco stalo. potvrzení (toas message) není přístupná, nevím, jestli se s tím dá něco udělat - nemá žádnou zpětnou vazbu, čtečka mu nepřečte "Náladu jsme úspěšně zaznamenali" - ale je možné, že na to jen nekliknul a tím pádem se nezobrazil toast - každopádně on ani nepozná, že na to má kliknout, není to ani jako obrázek, ani to není značené jako prvek
-nadpist Ahoj, jak se dnes cítíš - měl by být nadpis (technicky, aby to čtečka poznala)

-nadpis "S čím můžeme pomoci?" - by měl být nadpis (technicky, aby to čtečka poznala)

Co mi můze pomoci
---------------------------
nav: Home -> Chci si ublížit -> Co mi může pomoci
carrousell - dokáže projíždět tipy, ale stejně jako akční prvky, jsou neoznačené - je tedy potřeba odlišit klikací (tlačítka, dlaždice) od neklikacích (carrousell)

Sledování nálady
----------------------------
nav: Home -> Mé záznamy (dlaždice nebo spodní menu) -> Sledování nálady
-graf je obrázek - Michal tam neměl zadané žádné nálady, tak je otázka, jak by se to chovalo
-kalendář není úplně vhodný, lépe by bylo kdyby mohl vybírat - to už je asi opravené, v aplikaci se datum vybírá
-prvek uprostřed obrazovky - slyší, že tam něco je, ale nic to nedělá - možná je to ukazatel na grafu

tlačítko zpět popsat?? - obecně skrz celou aplikaci

Deník
---------------------
.přídání záznamu - nestandardní prvek
-u textových polí obecně by se měl zapisovat záznam s prvním velkým písmenem (platí obecně, ale je i v deníku) - nutí to lidi ťukat na shift

Improvement
-v Deníku možnost přidat náladu - to je to ideální místo na to

-záznamy v deníku jsou správně - chovají se jako položky nabídky
--akorát tam je někde prázdný řádek kvůli pozicování, to ničemu moc nevadí, ale není to úplně správně

Journal
--------------------------
-je správně, pochopitelné

Záznamy jídelníčku - ok, jediné co, tak by asi neměl být "přepínač" ale "zaškrtávací pole" ale to moc ničemu nevadí

Záznam nálady - nepřístupný
deník, jídelník, journal - přístupný a ok

**Comment by mzdm** [comment]
Něco jsem už upravoval (https://github.com/cesko-digital/nepanikar/pull/180), ale není to úplně vše z toho audia. Připadalo mi že tomu i technicky rozumí, tak ho možná můžem zkusit dostat na Github, aby se mohl podrobně k těm bodům vyjádřit jestli už jsou ok
